language: python
matrix:
  include:
#  - os: windows
#    python: '2.7'
  - os: linux
    dist: trusty
    sudo: false
    python: '2.7'
  - os: linux
    dist: trusty
    sudo: false
    python: '3.4'
  - os: linux
    dist: trusty
    sudo: false
    python: '3.5'
  - os: linux
    dist: trusty
    sudo: false
    python: '3.6'
  - os: linux
    dist: xenial
    sudo: required
    services:
      - docker
    python: '3.7'
    env: BUILD_SDIST=true
  - os: linux
    sudo: false
    python: pypy
  - os: linux
    sudo: false
    python: pypy3
  - os: osx
    language: objective-c
    env: PYENV_VERSION=2.7.12
  - os: osx
    language: objective-c
    env: PYENV_VERSION=3.5.5
  - os: osx
    language: objective-c
    env: PYENV_VERSION=3.6.5
before_install:
    - pip install pytest>=4.6.6 pytest-cov<=2.6.0 coveralls>=1.5.1 python-hosts colorama
script:
    - py.test --cov-report term-missing --cov hostman
after_success:
    coveralls
